config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

from trip_planner.core.views import ping

urlpatterns = [
    path("admin/", admin.site.urls),
    path("accounts/", include("allauth.urls")),
    path("", include("trip_planner.pages.urls", namespace="pages")),
    path("trips/", include("trip_planner.trips.urls", namespace="trips")),
    path("calendar/", include("trip_planner.calendars.urls", namespace="calendars")),
    path("markers/", include("trip_planner.markers.urls", namespace="markers")),
    path("ping/", ping, name="ping"),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

# Django debug_toolbar
if settings.DEBUG:
    import debug_toolbar

    urlpatterns += (path("__debug__/", include(debug_toolbar.urls)),)

trip_planner/markers/urls.py
from django.urls import path

from .api_views import MarkerViewSet, MarkerViewSetAllTrips
from .views import (
    MarkerCreateView,
    MarkerDeleteView,
    MarkerListView,
    MarkerListViewAllTrips,
    MarkerUpdateView,
)

app_name = "markers"
urlpatterns = [
    path("trips/", MarkerListViewAllTrips.as_view(), name="marker_list_all_trips"),
    path("trips/<int:trip_pk>/", MarkerListView.as_view(), name="marker_list"),
    path("trips/<int:trip_pk>/create/", MarkerCreateView.as_view(), name="marker_create"),
    # HACK, XXX below: hardcored into "layer.bindPopup" in "markers/marker_list.html" template
    path("trips/<int:trip_pk>/update/<int:pk>/", MarkerUpdateView.as_view(), name="marker_update"),
    # HACK, XXX below: hardcored into "layer.bindPopup" in "markers/marker_list.html" template
    path("trips/<int:trip_pk>/delete/<int:pk>/", MarkerDeleteView.as_view(), name="marker_delete"),
    path("api/trips/", MarkerViewSetAllTrips.as_view({"get": "list"}), name="api_all_trips_markers"),
    path("api/trips/<int:trip_pk>/", MarkerViewSet.as_view({"get": "list"}), name="api_trip_markers"),
]

trip_planner/pages/urls.py
from django.urls import path

from .views import ContactPageView, HomePageView

app_name = "pages"
urlpatterns = [
    path("", HomePageView.as_view(), name="home"),
    path("contact/", ContactPageView.as_view(), name="contact"),
]

trip_planner/trips/urls.py
from django.urls import path

from .views import (  # Trip Views; TripDay Views; Activity Views
    ActivityCreateView,
    ActivityDeleteView,
    ActivityUpdateView,
    TripCreateView,
    TripDayUpdateView,
    TripDeleteView,
    TripDetailView,
    TripListView,
    TripUpdateView,
    TripUpdateViewPicture,
)

app_name = "trips"
urlpatterns = [
    # Trip urls
    path("", TripListView.as_view(), name="trip_list"),
    path("create/", TripCreateView.as_view(), name="trip_create"),
    path("<int:pk>/", TripDetailView.as_view(), name="trip_detail"),
    path("<int:pk>/update/", TripUpdateView.as_view(), name="trip_update"),
    path("<int:pk>/delete/", TripDeleteView.as_view(), name="trip_delete"),
    path("<int:pk>/picture-update/", TripUpdateViewPicture.as_view(), name="trip_update_picture"),
    # TripDay urls
    path("<int:trip_pk>/days/<int:pk>/update/", TripDayUpdateView.as_view(), name="trip_day_update"),
    # Activity urls
    path("<int:trip_pk>/days/<int:pk>/add-activity/", ActivityCreateView.as_view(), name="activity_create"),
    path(
        "<int:trip_pk>/days/<int:trip_day_pk>/activities/<int:pk>/update/",
        ActivityUpdateView.as_view(),
        name="activity_update",
    ),
    path(
        "<int:trip_pk>/days/<int:trip_day_pk>/activities/<int:pk>/delete/",
        ActivityDeleteView.as_view(),
        name="activity_delete",
    ),
]

trip_planner/accounts/models.py
from django.contrib.auth.models import AbstractUser

# Create your models here.


class CustomUser(AbstractUser):
    pass

trip_planner/core/models.py
from django.db import models

# Create your models here.


class TimeStampedModel(models.Model):
    """
    An abstract base class model that provides self-updating ``created`` and ``modified`` fields.
    """

    created_at = models.DateTimeField(auto_now_add=True)
    modified_at = models.DateTimeField(auto_now=True)

    class Meta:
        abstract = True


# consider adding abstract class for soft delete TODO
# deleted_at = models.DateTimeField(null=True, blank=True)
# is_deleted = models.BooleanField(default=False)

trip_planner/markers/models.py
from django.conf import settings
from django.contrib.gis.db import models as gis_models
from django.db import models
from django.urls.base import reverse

from trip_planner.trips.models import Trip

# Create your models here.


class Marker(gis_models.Model):
    """
    A map marker with name and location.
    """

    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    trip = models.ForeignKey(Trip, on_delete=models.CASCADE)
    name = models.CharField("Marker name", max_length=100, help_text="This is the name of your map marker.")
    geom = gis_models.GeometryField("Marker", help_text="This is the location point or area of your map marker.")

    def __str__(self) -> str:
        return self.name

    def get_absolute_url(self):
        return reverse("markers:marker_list", kwargs={"trip_pk": self.trip.pk})

trip_planner/accounts/forms.py
from django.contrib.auth import get_user_model
from django.contrib.auth.forms import UserChangeForm, UserCreationForm

CustomUser = get_user_model()


# TODO: are we using this form now that we have django-allauth?
class CustomUserCreationForm(UserCreationForm):
    class Meta:
        model = CustomUser
        fields = (
            "email",
            "username",
        )


class CustomUserChangeForm(UserChangeForm):
    class Meta:
        model = CustomUser
        fields = (
            "email",
            "username",
        )

trip_planner/markers/forms.py
from django import forms
from leaflet.forms.widgets import LeafletWidget

from .models import Marker

# Marker Forms


class MarkerCreateForm(forms.ModelForm):
    class Meta:
        model = Marker
        fields = (
            "name",
            "geom",
        )
        widgets = {
            "geom": LeafletWidget(),
        }


class MarkerUpdateForm(forms.ModelForm):
    class Meta:
        model = Marker
        fields = (
            "name",
            "geom",
        )
        widgets = {
            "geom": LeafletWidget(),
        }

trip_planner/pages/forms.py
from django import forms
from django.forms.widgets import Textarea


class ContactForm(forms.Form):
    name = forms.CharField(required=True, max_length=50)
    email = forms.EmailField(
        required=False, help_text="(optional) Kindly provide your email to allow me to respond to you."
    )
    subject = forms.CharField(required=True, max_length=75)
    message = forms.CharField(widget=Textarea, required=True, max_length=1200)

trip_planner/calendars/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.db.models import Prefetch
from django.views.generic.list import ListView

from trip_planner.trips.models import Activity, Trip, TripDay


class CalendarView(LoginRequiredMixin, ListView):
    template_name = "calendars/calendar.html"
    model = Trip

    def get_queryset(self, *args, **kwargs):
        """
        Before returning queryset, prefetches Trip Days and Activities for user's Trips.
        """
        prefetched_data = Prefetch(
            "trip_days",
            queryset=TripDay.objects.order_by("date").prefetch_related(
                Prefetch("activities", queryset=Activity.objects.order_by("time"), to_attr="prefetched_activities")
            ),
            to_attr="prefetched_trip_days",
        )
        qs = super().get_queryset(*args, **kwargs).filter(user=self.request.user).prefetch_related(prefetched_data)
        return qs

trip_planner/core/views.py
from django.http import JsonResponse


def ping(request):
    data = {"ping": "pong!"}
    return JsonResponse(data)

trip_planner/maps/views.py
from django.views.generic.base import TemplateView
from django.views.generic.edit import CreateView
from django.contrib.auth.mixins import LoginRequiredMixin

from .models import Marker
from .forms import MarkerCreateForm

from trip_planner.trips.models import Trip


# Create your views here.


class MarkerListView(LoginRequiredMixin, TemplateView):

    template_name = 'maps/marker_list.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['trip_pk'] = self.kwargs['trip_pk']
        return context


class MarkerCreateView(LoginRequiredMixin, CreateView):
    
    model = Marker
    template_name = 'maps/marker_form.html'
    form_class = MarkerCreateForm

    def form_valid(self, form):
        form.instance.user = self.request.user
        form.instance.trip = Trip.objects.get(pk=self.kwargs['trip_pk'])
        return super().form_valid(form)

trip_planner/markers/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.urls.base import reverse_lazy
from django.views.generic.base import TemplateView
from django.views.generic.edit import CreateView, DeleteView, UpdateView

from trip_planner.core.mixins import UserPassesOwnerTestMixin
from trip_planner.trips.models import Trip

from .forms import MarkerCreateForm, MarkerUpdateForm
from .models import Marker

# Single Trip Views


class MarkerListView(LoginRequiredMixin, UserPassesOwnerTestMixin, TemplateView):
    template_name = "markers/marker_list.html"
    owner_mixin_model = Trip  # custom field for UserPassesOwnerTestMixin

    def test_func(self) -> bool:
        """Pass custom pk param to UserPassesOwnerTestMixin."""
        return super().test_func(pk_param="trip_pk")


class MarkerCreateView(LoginRequiredMixin, UserPassesOwnerTestMixin, CreateView):
    model = Marker
    template_name = "markers/marker_form.html"
    form_class = MarkerCreateForm
    owner_mixin_model = Trip  # custom field for UserPassesOwnerTestMixin

    def test_func(self) -> bool:
        """Pass custom pk param to UserPassesOwnerTestMixin."""
        return super().test_func(pk_param="trip_pk")

    def form_valid(self, form):
        form.instance.user = self.request.user
        form.instance.trip = Trip.objects.get(pk=self.kwargs["trip_pk"])
        return super().form_valid(form)


class MarkerUpdateView(LoginRequiredMixin, UserPassesOwnerTestMixin, UpdateView):
    model = Marker
    template_name = "markers/marker_update_form.html"
    form_class = MarkerUpdateForm
    owner_mixin_model = Trip  # custom field for UserPassesOwnerTestMixin

    def test_func(self) -> bool:
        """Pass custom pk param to UserPassesOwnerTestMixin."""
        return super().test_func(pk_param="trip_pk")

    def form_valid(self, form):
        form.instance.user = self.request.user
        form.instance.trip = Trip.objects.get(pk=self.kwargs["trip_pk"])
        return super().form_valid(form)


class MarkerDeleteView(LoginRequiredMixin, UserPassesOwnerTestMixin, DeleteView):
    model = Marker
    template_name = "markers/marker_delete.html"
    owner_mixin_model = Trip  # custom field for UserPassesOwnerTestMixin

    def test_func(self) -> bool:
        """Pass custom pk param to UserPassesOwnerTestMixin."""
        return super().test_func(pk_param="trip_pk")

    def get_success_url(self) -> str:
        trip_pk = self.kwargs["trip_pk"]
        return reverse_lazy("markers:marker_list", kwargs={"trip_pk": trip_pk})


# All Trips Views


class MarkerListViewAllTrips(LoginRequiredMixin, TemplateView):
    template_name = "markers/marker_list_all_trips.html"

trip_planner/pages/views.py
from django.conf import settings
from django.contrib import messages
from django.core.mail import send_mail
from django.http import request
from django.urls import reverse_lazy
from django.views.generic.base import TemplateView
from django.views.generic.edit import FormView

from .forms import ContactForm

# Home Page Views


class HomePageView(TemplateView):
    template_name = "pages/home.html"


# Contact Page Views


class ContactPageView(FormView):
    template_name = "pages/contact.html"
    form_class = ContactForm
    success_url = reverse_lazy("pages:home")

    def form_valid(self, form):
        """
        Sends email from settings.DEFAULT_FROM_EMAIL to itself with the message provided in the form.
        """
        cleaned_name = form.cleaned_data.get("name")
        cleaned_email = form.cleaned_data.get("email")
        cleaned_subject = form.cleaned_data.get("subject")
        cleaned_message = form.cleaned_data.get("message")

        email_message = f"{cleaned_name} / {cleaned_email} said:"
        email_message += f"\n\nsubject: {cleaned_subject}"
        email_message += f"\n\nmessage: {cleaned_message}"

        send_mail(
            subject=f"Trip Planner: {cleaned_name} / {cleaned_email} said:",
            message=email_message,
            from_email=settings.DEFAULT_FROM_EMAIL,
            recipient_list=[
                settings.DEFAULT_FROM_EMAIL,
            ],
        )

        messages.success(self.request, f"Your message was succesfully sent. Thank you for your input, {cleaned_name}!")

        return super().form_valid(form)

trip_planner/trips/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.db.models import Prefetch
from django.urls import reverse_lazy
from django.views.generic.detail import DetailView
from django.views.generic.edit import CreateView, DeleteView, UpdateView
from django.views.generic.list import ListView

from trip_planner.core.mixins import UserPassesOwnerTestMixin

from .forms import (
    ActivityCreateForm,
    ActivityUpdateForm,
    TripCreateForm,
    TripDayUpdateForm,
    TripUpdateForm,
    TripUpdateFormPicture,
)
from .models import Activity, Trip, TripDay

# Trip Views


class TripListView(LoginRequiredMixin, ListView):
    model = Trip
    template_name = "trips/trip_list.html"
    context_object_name = "trip_list"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["trip_list"] = context["trip_list"].filter(user=self.request.user).order_by("start_date")
        return context


class TripDetailView(LoginRequiredMixin, UserPassesOwnerTestMixin, DetailView):
    model = Trip
    template_name = "trips/trip_detail.html"
    context_object_name = "trip"

    def get_queryset(self, *args, **kwargs):
        """
        Before returning queryset, prefetches Trip Days for a given Trip and Activities for these Trip Days.
        """
        prefetched_data = Prefetch(
            "trip_days",
            queryset=TripDay.objects.order_by("date").prefetch_related(
                Prefetch("activities", queryset=Activity.objects.order_by("time"), to_attr="prefetched_activities")
            ),
            to_attr="prefetched_trip_days",
        )
        qs = super().get_queryset(*args, **kwargs).prefetch_related(prefetched_data)
        return qs


class TripCreateView(LoginRequiredMixin, CreateView):
    model = Trip
    template_name = "trips/trip_form.html"
    form_class = TripCreateForm

    def form_valid(self, form):
        form.instance.user = self.request.user
        return super().form_valid(form)


class TripUpdateView(LoginRequiredMixin, UserPassesOwnerTestMixin, UpdateView):
    model = Trip
    template_name = "trips/trip_update_form.html"
    form_class = TripUpdateForm


class TripUpdateViewPicture(LoginRequiredMixin, UserPassesOwnerTestMixin, UpdateView):
    model = Trip
    template_name = "trips/trip_update_form_picture.html"
    form_class = TripUpdateFormPicture


class TripDeleteView(LoginRequiredMixin, UserPassesOwnerTestMixin, DeleteView):
    model = Trip
    template_name = "trips/trip_delete.html"
    success_url = reverse_lazy("trips:trip_list")


# TripDay Views


class TripDayUpdateView(LoginRequiredMixin, UserPassesOwnerTestMixin, UpdateView):
    model = TripDay
    template_name = "trips/trip_day_update_form.html"
    form_class = TripDayUpdateForm


# Activity Views


class ActivityCreateView(LoginRequiredMixin, UserPassesOwnerTestMixin, CreateView):
    model = Activity
    template_name = "trips/activity_form.html"
    form_class = ActivityCreateForm
    owner_mixin_model = TripDay  # custom field for UserPassesOwnerTestMixin

    def form_valid(self, form):
        form.instance.user = self.request.user
        form.instance.trip = Trip.objects.get(pk=self.kwargs["trip_pk"])
        form.instance.day = TripDay.objects.get(pk=self.kwargs["pk"])
        return super().form_valid(form)


class ActivityUpdateView(LoginRequiredMixin, UserPassesOwnerTestMixin, UpdateView):
    model = Activity
    template_name = "trips/activity_update_form.html"
    form_class = ActivityUpdateForm

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["trip_pk"] = self.kwargs["trip_pk"]
        context["trip_day_pk"] = self.kwargs["trip_day_pk"]
        return context

    def get_queryset(self, *args, **kwargs):
        trip_day_pk = self.kwargs["trip_day_pk"]
        qs = super().get_queryset(*args, **kwargs).filter(day=trip_day_pk)
        return qs


class ActivityDeleteView(LoginRequiredMixin, UserPassesOwnerTestMixin, DeleteView):
    model = Activity
    template_name = "trips/activity_delete.html"

    def get_success_url(self, **kwargs):
        success_url = reverse_lazy("trips:trip_detail", kwargs={"pk": self.kwargs["trip_pk"]})
        return success_url

trip_planner/templates/trips/activity_delete.html
<!DOCTYPE html>
{% extends 'base.html' %}

{% block title %}
    Trips | Trip Planner
{% endblock title %}

{% block header %}
    Trips
{% endblock header %}

{% block content %}

    {{ block.super }}

    <br>
    
    <div class="card form-max-width mx-auto">
        <h5 class="card-header text-center">
            Delete the trip day activity
        </h5>
        <div class="card-body">
            <p>Are you sure you want to delete this activity:
            <br><span class="fw-bolder">{{ activity.title }}</span>
            <br>from <span class="fw-bolder">{{ activity.day }}</span> of <span class="fw-bolder">{{ activity.trip }}</span> trip?</p>
            <form method="post">
                {% csrf_token %}
                <div class="text-end">
                    <button class="btn btn-danger" type="submit" value="Confirm">Confirm deletion</button>
                </div>
            </form>
        </div>
    </div>

{% endblock content %}

trip_planner/templates/trips/activity_form.html
<!DOCTYPE html>
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block title %}
    Trips | Trip Planner
{% endblock title %}

{% block header %}
    Trips
{% endblock header %}

{% block content %}

    {{ block.super }}

    <br>
    
    <div class="card form-max-width mx-auto">
        <h5 class="card-header text-center">
            Create a trip day activity
        </h5>
        <div class="card-body">
            <form class="form-max-width mx-auto" method="post">
                {% csrf_token %}
                {{ form|crispy }}
                <div class="text-end">
                    <button class="btn btn-primary" type="submit">Create activity</button>
                </div>
            </form>
        </div>
    </div>

{% endblock content %}

trip_planner/templates/trips/activity_update_form.html
<!DOCTYPE html>
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block title %}
    Trips | Trip Planner
{% endblock title %}

{% block header %}
    Trips
{% endblock header %}

{% block content %}

    {{ block.super }}

    <br>
    
    <div class="card form-max-width mx-auto">
        <h5 class="card-header text-center">
            Update the trip day activity
        </h5>
        <div class="card-body">
            <form class="form-max-width mx-auto" method="post">
                {% csrf_token %}
                {{ form|crispy }}
                <div class="text-end">
                    <button class="btn btn-primary" type="submit">Update activity</button>
                </div>
            </form>
        </div>
    </div>

{% endblock content %}

trip_planner/templates/trips/trip_day_update_form.html
<!DOCTYPE html>
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block title %}
    Trips | Trip Planner
{% endblock title %}

{% block header %}
    Trips
{% endblock header %}

{% block content %}

    {{ block.super }}

    <br>
    
    <div class="card form-max-width mx-auto">
        <h5 class="card-header text-center">
            Update trip day notes
        </h5>
        <div class="card-body">
            <form class="form-max-width mx-auto" method="post">
                {% csrf_token %}
                {{ form|crispy }}
                <div class="text-end">
                    <button class="btn btn-primary" type="submit">Update notes</button>
                </div>
            </form>
        </div>
    </div>

{% endblock content %}

trip_planner/templates/trips/trip_delete.html
<!DOCTYPE html>
{% extends 'base.html' %}

{% block title %}
    Trips | Trip Planner
{% endblock title %}

{% block header %}
    Trips
{% endblock header %}

{% block content %}

    {{ block.super }}

    <br>
    
    <div class="card form-max-width mx-auto">
        <h5 class="card-header text-center">
            Delete the trip
        </h5>
        <div class="card-body">
            <p>Are you sure you want to delete this trip: 
            <br><span class="fw-bolder">{{ trip.title }}</span>?</p>
            <form method="post">
                {% csrf_token %}
                <div class="text-end">
                    <button class="btn btn-danger" type="submit" value="Confirm">Confirm deletion</button>
                </div>
            </form>
        </div>
    </div>

{% endblock content %}

trip_planner/templates/trips/trip_detail.html
<!DOCTYPE html>
{% extends 'base.html' %}
{% load static %}

{% block title %}
    Trips | Trip Planner
{% endblock title %}

{% block header %}
    Trips
{% endblock header %}

{% block content %}

    {{ block.super }}
    
    <br>

    <div class="container content-max-width g-0">
        <div class="card content-card-max-width mx-auto text-center">
            <div class="card-header">
                <h4 class="card-title">{{ trip.title }}</h4>
                <p class="card-text">{{ trip.start_date }} - {{ trip.end_date }}</p>
            </div>
            <div class="card-body">
                {% if trip.picture %}
                    <img class='trip__card-image mb-2' src="{{ trip.picture.url }}" alt="trip-img">
                {% else %}
                    <img src="{% static '/img/placeholder-trip-img.png' %}" class="trip__card-image mb-2" alt="placeholder-trip-img">
                {% endif %}
                <hr class="trip__card-hr">
                {% if trip.notes %}
                    <p class="card-text">{{ trip.notes }}</p>
                {% else %}
                    <p class="card-text text-muted">There is no description of this trip yet.</p>                            
                {% endif %}
                <div class="text-end">
                    <a href="{% url 'trips:trip_update' trip.pk %}" class="btn btn-primary trip__card-button-width mb-1">Update details</a>
                    <a href="{% url 'trips:trip_update_picture' trip.pk %}" class="btn btn-primary trip__card-button-width mb-1">Update picture</a>
                    <a href="{% url 'markers:marker_list' trip.pk %}" class="btn btn-primary trip__card-button-width mb-1">Show Map</a>
                    <a href="{% url 'trips:trip_delete' trip.pk %}" class="btn btn-outline-danger trip__card-button-width mb-1">Delete Trip</a>
                </div>
            </div>
        </div>
        
        <br><br>
        
        <div class="row row-cols-1 row-cols-md-2 row-cols-xl-3 row-cols-xxl-4 g-1 g-md-2 g-xl-3">
            {% for trip_day in trip.prefetched_trip_days %}
                <div class="col">
                    <div class="card">
                        <div class="trip-day-anchor" id="{{ trip_day }}" style="position:relative;top:-3.5rem"></div>
                        <div class="card-header">
                            <h6 class="card-title text-center">{{ trip_day }} <br></h6>
                            <h6 class="text-center">{{ trip_day.date }}</h6>
                        </div>
                        <div class="card-body">
                            {% if trip_day.notes %}
                                <p class="card-text">{{ trip_day.notes }}</p>
                            {% else %}
                                <p class="card-text text-muted text-center">There are no notes for the day yet.</p>
                            {% endif %}
                        </div>
                        <div class="card-header card-footer"></div>
                            {% if trip_day.prefetched_activities %}
                                <ul class="list-group list-group-flush">
                                    {% for activity in trip_day.prefetched_activities %}
                                        <li class="trip__card-activity-item list-group-item d-flex justify-content-between align-items-center">
                                            <div class="d-inline">
                                                <span class="fw-light fst-italic">{{ activity.time }}:</span><br>
                                                <span>{{ activity.title }}</span>
                                            </div>
                                            <div class="btn-group-vertical" role="group" aria-label="Activity buttons">
                                                <a href="{% url 'trips:activity_update' trip.pk trip_day.pk activity.pk %}" type="button" class="btn btn-outline-secondary btn-sm">Update</a>
                                                <a href="{% url 'trips:activity_delete' trip.pk trip_day.pk activity.pk %}" type="button" class="btn btn-outline-secondary btn-sm">Delete</a>
                                            </div>
                                        </li>
                                    {% endfor %}
                                </ul>
                            {% else %}
                                <br>
                                <p class="card-text text-muted text-center">There are no activities for the day yet.</p>
                                <hr class="trip__card-day-hr">
                            {% endif %}
                        <div class="card-body text-end">
                            <a href="{% url 'trips:trip_day_update' trip.pk trip_day.pk %}" type="button" class="btn btn-sm btn-outline-primary">Update notes</a>                        
                            <a href="{% url 'trips:activity_create' trip.pk trip_day.pk %}" type="button" class="btn btn-sm btn-outline-primary">Add activity</a>
                        </div>
                    </div>
                </div>
            {% endfor %}
        </div>
        <br>
    </div>

{% endblock content %}

trip_planner/templates/trips/trip_form.html
<!DOCTYPE html>
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block title %}
    Trips | Trip Planner
{% endblock title %}

{% block header %}
    Trips
{% endblock header %}

{% block content %}

    {{ block.super }}
    
    <br>

    <div class="card form-max-width mx-auto">
        <h5 class="card-header text-center">
            Create a trip
        </h5>
        <div class="card-body">
            <form class="form-max-width mx-auto" method="post">
                {% csrf_token %}
                {{ form|crispy }}
                <div class="text-end">
                    <button class="btn btn-primary" type="submit">Create trip</button>
                </div>
            </form>
        </div>
    </div>

{% endblock content %}

trip_planner/templates/trips/trip_list.html
<!DOCTYPE html>
{% extends 'base.html' %}
{% load static %}

{% block title %}
    Trips | Trip Planner
{% endblock title %}

{% block header %}
    Trips
{% endblock header %}

{% block content %}

    {{ block.super }}

    <br>

    <div class="container content-max-width g-0">
        <div class="card content-card-max-width mx-auto">
            <h5 class="card-header text-center">
                All Trips
            </h5>
            <div class="card-body">
                <p>On this page you can create and view all your trips. Have fun!</p>
                <div class="d-grid gap-2 col-12 col-sm-8 col-md-6 mx-auto">
                    <a href="{% url 'trips:trip_create' %}" class="btn btn-primary btn-lg" type="button"><strong>CREATE A NEW TRIP!</strong></a>
                </div>
            </div>
        </div>

        <br>
        
        <div class="row row-cols-1 row-cols-sm-2 row-cols-lg-3 g-3">
            {% for trip in trip_list %}
            <div class="card__max-width col">
                <div class="card shadow-sm">
                    {% if trip.picture %}
                        <a href="{% url 'trips:trip_detail' trip.pk %}">
                            <img src="{{ trip.picture.url }}" class="trip__card-image card-img-top" alt="trip-img">
                        </a>
                    {% else %}
                        <a href="{% url 'trips:trip_detail' trip.pk %}">
                            <img src="{% static '/img/placeholder-trip-img.png' %}" class="card-img-top" alt="placeholder-trip-img">
                        </a>
                    {% endif %}
                    <div class="card-body">
                        <h3 class="trip__card-title text-center">{{ trip.title }}</h3>
                        <h6 class="trip__card-date text-center">{{ trip.start_date }} - {{ trip.end_date }}</h6>
                        <hr class="trip__card-hr">
                        <div class="card__text-truncate-container">
                            {% if trip.notes %}
                                <p class="card-text text-truncate">{{ trip.notes }}</p>
                            {% else %}
                                <p class="card-text text-muted">There are no notes for the trip yet.</p>
                            {% endif %}
                        </div>
                        <br>
                        <div class="col text-end">
                            <div class="btn-group">
                                <a href="{% url 'trips:trip_detail' trip.pk %}" type="button" class="btn btn-outline-primary"><strong>Details</strong></a>
                                <a href="{% url 'markers:marker_list' trip.pk %}" type="button" class="btn btn-outline-primary"><strong>Map</strong></a>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            {% endfor %}
        </div>

        <br><br>
    </div>
    

{% endblock content %}